### ISSUE TITLE
Can you update it for IDA PRO 9.0?

### ISSUE THREAD

**Issue by maskelihileci** [herosi/classinformer#4]
![image](https://github.com/user-attachments/assets/7fd4dccc-5e7e-47f9-baa4-524a76c0d300)

**Comment by rohitab** [comment]
I have built the IDA Class Informer plugin for IDA 9.0 Beta.
Here are the changes:

- Add support for IDA 9.0 Beta.
- Combine 64-bit `IDA_ClassInformer_PlugIn64.dlL` 32-bit on 64-bit `IDA_ClassInformer_PlugIn3264.dlL` into a single DLL `ClassInformer64.dll` that works for both 32-bit and 64-bit files.
- Fix issue: `** customizeChooseWindow(): "IDADockWidget" not found!`
- Fix issue where stylesheet was not being applied.
- Fix issue: `** customizeChooseWindow(): "TChooserView" not found!`
- Fix issue where row height and sort order were not being applied.
- Auto size all columns to fit and stretch the last column.
- Automatically select the first row when the Class Informer window is opened.
- Fix issue: `* Already active. Please close the chooser window first to run it again.`
- Automatically switch to Class Informer if it is open and the user runs it again.
- Retain settings from previous runs in the current instance.
- Reduce font size from `14px` to `12px` and reduce row height from `24` to `22`.
- Add padding to columns.
- Add a checkbox **_at named locations_** to allow structures to be placed at named locations.
- Add my name to credits, and update UI so that previous author names are visible.


I will post the updated code to GitHub soon and/or submit a PR.
Please note that there are still quite a few bugs from the original code, which I have not fixed yet.

[IDA Class Informer 2.8 for IDA 9.0 Beta.zip](https://github.com/user-attachments/files/16621475/IDA.Class.Informer.2.8.for.IDA.9.0.Beta.zip)

**Comment by rohitab** [comment]
I've updated Class Informer to `2.9`. You can download binaries for IDA 9.0 and older versions from [Releases](https://github.com/rohitab/ClassInformer/releases).

Source code is available on https://github.com/rohitab/ClassInformer

**Comment by 0x6461726B** [comment]
> I've updated Class Informer to `2.9`. You can download binaries for IDA 9.0 and older versions from [Releases](https://github.com/rohitab/ClassInformer/releases).
> 
> Source code is available on https://github.com/rohitab/ClassInformer

thank you for updating, i am wondering if its classinformers fault or issue with the update, but classinformer doesn't work when scanning a rebased (0x0) database. I have tested both rebased and non rebased same binary, and on non rebased it worked, on rebased 0 results.

**Comment by rohitab** [comment]
I am unable to reproduce your issue. I rebased two different binaries and ran Class Informer. In both cases, it worked as expected. Note that Class Informer scans segments using their start address and size, so rebasing the image should not make any difference. Do you see any indication of failure, like error messages in the output window?

**Comment by 0x6461726B** [comment]
i apologize, the problem was i didn't try 2 different binaries, it works as expected it was the binary which had the issue

**Comment by herosi** [comment]
Thank you for your cooperation, @rohitab.
I finally take the PR, although I needed to change a few points to work on IDA 9.0 release. That:s why I released v2.91.
